create table service_requests (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    full_name varchar(120) not null,
    phone varchar(20) not null,
    address varchar(255) not null,
    service_type varchar(80) not null,
    preferred_time varchar(120),
    note varchar(1000),
    status varchar(20) not null default 'NEW',
    admin_note varchar(1000),
    contacted_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_service_requests_user foreign key (user_id) references users(id)
);

create index idx_service_requests_status_created_at on service_requests(status, created_at);
create index idx_service_requests_user_id on service_requests(user_id);
