alter table service_requests
    add column staff_result_note varchar(1000),
    add column complaint varchar(1000),
    add column staff_contacted_at timestamp,
    add column staff_completed_at timestamp,
    add column customer_confirmed_at timestamp;

update service_requests
set staff_result_note = admin_note,
    staff_completed_at = completed_at,
    customer_confirmed_at = completed_at,
    status = 'COMPLETED'
where status = 'DONE';

update service_requests
set status = 'ASSIGNED'
where status = 'SCHEDULED';

create table service_reviews (
    id bigint generated by default as identity primary key,
    service_request_id bigint not null unique,
    user_id bigint not null,
    rating integer not null,
    content varchar(1000) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_service_reviews_request foreign key (service_request_id) references service_requests(id),
    constraint fk_service_reviews_user foreign key (user_id) references users(id),
    constraint ck_service_reviews_rating check (rating between 1 and 5)
);

create index idx_service_reviews_created_at on service_reviews(created_at desc);
