import { useEffect, useState } from 'react'
import api, { errorMessage } from '../../services/api'
import { money } from '../../services/format'

const empty = { code: '', name: '', type: 'PERCENT', value: '', minOrderAmount: 0, maxDiscount: '', startAt: '', endAt: '', usageLimit: '', active: true }
export default function AdminCoupons() {
  const [items, setItems] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null)
  const load = () => api.get('/admin/coupons').then(r => setItems(r.data))
  useEffect(() => { load() }, [])
  const edit = x => { setEditing(x.id); setForm({ code: x.code, name: x.name, type: x.type, value: x.value, minOrderAmount: x.minOrderAmount, maxDiscount: x.maxDiscount || '', startAt: x.startAt?.slice(0,16) || '', endAt: x.endAt?.slice(0,16) || '', usageLimit: x.usageLimit || '', active: x.active }) }
  const reset = () => { setEditing(null); setForm(empty) }
  const submit = async e => { e.preventDefault(); const payload = { ...form, value: Number(form.value), minOrderAmount: Number(form.minOrderAmount || 0), maxDiscount: form.maxDiscount ? Number(form.maxDiscount) : null, usageLimit: form.usageLimit ? Number(form.usageLimit) : null, startAt: form.startAt || null, endAt: form.endAt || null }; try { editing ? await api.put(`/admin/coupons/${editing}`, payload) : await api.post('/admin/coupons', payload); reset(); load() } catch (err) { alert(errorMessage(err)) } }
  return <div className="admin-page"><div className="admin-heading"><div><span className="eyebrow">CHƯƠNG TRÌNH ƯU ĐÃI</span><h1>Mã giảm giá</h1></div></div><section className="admin-panel admin-form-panel"><h2>{editing ? 'Sửa mã giảm giá' : 'Tạo mã mới'}</h2><form onSubmit={submit}><div className="form-grid three"><label>Mã<input required value={form.code} onChange={e => setForm({ ...form, code: e.target.value.toUpperCase() })}/></label><label>Tên chương trình<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>Loại<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}><option value="PERCENT">Phần trăm</option><option value="FIXED">Số tiền cố định</option></select></label></div><div className="form-grid four"><label>Giá trị<input type="number" required min="1" value={form.value} onChange={e => setForm({ ...form, value: e.target.value })}/></label><label>Đơn tối thiểu<input type="number" min="0" value={form.minOrderAmount} onChange={e => setForm({ ...form, minOrderAmount: e.target.value })}/></label><label>Giảm tối đa<input type="number" min="0" value={form.maxDiscount} onChange={e => setForm({ ...form, maxDiscount: e.target.value })}/></label><label>Giới hạn lượt<input type="number" min="1" value={form.usageLimit} onChange={e => setForm({ ...form, usageLimit: e.target.value })}/></label></div><div className="form-grid two"><label>Bắt đầu<input type="datetime-local" value={form.startAt} onChange={e => setForm({ ...form, startAt: e.target.value })}/></label><label>Kết thúc<input type="datetime-local" value={form.endAt} onChange={e => setForm({ ...form, endAt: e.target.value })}/></label></div><label className="checkbox-label"><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })}/> Đang hoạt động</label><div className="form-actions"><button className="btn btn-primary">{editing ? 'Lưu thay đổi' : 'Tạo mã'}</button>{editing && <button type="button" className="btn btn-soft" onClick={reset}>Hủy</button>}</div></form></section><section className="admin-panel"><h2>Danh sách mã</h2><div className="coupon-grid">{items.map(x => <article key={x.id} className={x.active ? '' : 'disabled'}><div className="coupon-cut left"/><div className="coupon-cut right"/><span>{x.code}</span><h3>{x.type === 'PERCENT' ? `Giảm ${x.value}%` : `Giảm ${money(x.value)}`}</h3><p>Đơn từ {money(x.minOrderAmount)}{x.maxDiscount && ` · Tối đa ${money(x.maxDiscount)}`}</p><small>Đã dùng {x.usedCount}/{x.usageLimit || '∞'} lượt</small><div className="row-actions"><button onClick={() => edit(x)}>Sửa</button><button className="danger-link" onClick={async () => { await api.delete(`/admin/coupons/${x.id}`); load() }}>Tắt</button></div></article>)}</div></section></div>
}
